FROM node:20-alpine

WORKDIR /usr/src/app

COPY package*.json ./
COPY tsconfig.json ./

RUN npm install && npm cache clean --force

COPY . .

ENV NODE_ENV=development

EXPOSE 8080

CMD ["npx", "ts-node-dev", "--respawn", "src/server.ts"]